# Generated by Django 4.0.4 on 2022-06-05 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trajects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart', models.CharField(max_length=100)),
                ('arrivel', models.CharField(max_length=100)),
                ('traject', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Trajet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateDepart', models.DateField(default='2000-12-31')),
                ('gareDepart', models.CharField(default='gare', max_length=100)),
                ('timeDepart', models.TimeField(default='00:00:00')),
                ('gareArrivel', models.CharField(default='gare', max_length=100)),
                ('timeArrivel', models.TimeField(default='00:00:00')),
                ('link', models.CharField(max_length=200)),
                ('correspondance', models.BooleanField(default=True)),
                ('gareDepartCorr', models.CharField(default='gare', max_length=100)),
                ('timeDepartCorr', models.TimeField(default='00:00:00')),
                ('gareArrivelCorr', models.CharField(default='gare', max_length=100)),
                ('timeArrivelCorr', models.TimeField(default='00:00:00')),
                ('linkCorr', models.CharField(default='link', max_length=200)),
            ],
        ),
    ]
