# Generated by Django 4.0.4 on 2022-06-06 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOptimizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trajet',
            name='gareArrivelCorr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trajet',
            name='gareDepartCorr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trajet',
            name='linkCorr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='trajet',
            name='timeArrivelCorr',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trajet',
            name='timeDepartCorr',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
